### ISSUE TITLE
Compare recorded runs with the CLI

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#10]
Once the developer recorded metadata for one or more runs of an experiment it should be possible to compare the runs.

**Requirements**
- [x] You should be able to compare runs to select the best one for deployment
- [x] You should be able to configure how the runs are compared with commandline arguments

**Comment by MichielLangen** [comment]
In the cli it is very hard to compare runs. There is no way of knowing what is relevant for a user, should a metric be compared and the highest value be returned. Only this doesn't work for some metrics like 'Loss' where you would want the lowest value. So we decided to give an overview of the metrics that need to be compared. Later in the dashboard a real comparison can be done using graphs

**Comment by MichielLangen** [comment]
All requirements are met for issue, it will now be closed
