### ISSUE TITLE
Switch between server and local tracking

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#12]
As a developer
I want to switch between server and local experiment tracking
So that I can work alone and in a team with others

**Scenario: Switch to local mode**
Given I configured observatory to track experiments remotely with `mode=remote`
When I configure observatory to track experiments locally with `mode=local`
And I start a new experiment run
Then the local client is used to record the run

**Scenario: Switch to remote mode**
Given I configured observatory to track experiments remotely with `mode=local`
When I configure observatory to track experiments locally with `mode=remote`
And I start a new experiment run
Then the remote client is used to record the run

Belongs to epic: #8

**Comment by MichielLangen** [comment]
configuring observatoy to track metrics local or remote will be done using the state pattern

_TrackingSession state pattern diagram_
![sessionstatepattern](https://user-images.githubusercontent.com/28343855/53075391-50dc0200-34ed-11e9-943e-920f56768376.png)

**Comment by MichielLangen** [comment]
during development we decided there will be no HTTPClient. Now the ServerState will handle the 
http-requests. Sink will stay, because this will also be used on the server to save metadata.
