### ISSUE TITLE
Use local tracking with sensible defaults for the first-run experience

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#13]
As a developer
I want to start using observatory with sensible default
So that I don't need to put a lot of effort in to get started

**Scenario: Start a run without configuring anything**
Given I haven't configured anything
When I start a new run
Then all metadata is stored in the local elasticsearch instance

Belongs to epic: #8

**Comment by MichielLangen** [comment]
Since #11 is skipped, All the metadata will be saved using the new storing mechanism intead of using elasticsearch
