### ISSUE TITLE
experiment names must have a letter in the name

### ISSUE THREAD

**Issue by MichielLangen** [wmeints/observatory#38]
Experiment names should be able to just be numbers
Now is has to contain letter in order to be valid
Letters and numbers mixed is valid now

AssertionError: experiment is invalid. It can contain lower-case alpha-numeric characters and dashes only.

**Comment by wmeints** [comment]
Previously you'd need to limit what could be set as experiment name because we were using elasticsearch. I don't think we really need it anymore. It would be nice if we could limit the length of the names to prevent problems in the storage. Not sure what the max length is in storage though.
